jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone storybook-repo
        run: |
          git clone https://github.com/judgedice/storybook-repo.git storybook-repo

      - name: Change directory to storybook-repo
        run: cd storybook-repo && echo "Now inside storybook-repo"

      # Add further steps here, like building, copying Storybook output, committing, etc.